apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
  name: redis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: redis-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: redis-deployment
    spec:
      containers:
      - image: redis
        name: redis-deployment
        env:
        - name: "POSTGERS_USER"
          valueFrom:
            secretKeyRef:
              name: "test"
              key: username
        resources: {}
status: {}
