apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: redis-deployment
    created_by: blacksmith
  name: redis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: redis-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: redis-deployment
    spec:
      containers:
      - image: redis
        name: redis-deployment
        resources: {}
status: {}
