apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: postgres-deployment
  name: postgres-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: postgres-deployment
  type: NodePort
status:
  loadBalancer: {}
